# Generated by Django 3.1.7 on 2021-03-31 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210331_1104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailForm',
        ),
    ]
