# Generated by Django 3.1.3 on 2020-11-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201120_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='service',
            name='period',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
