# Generated by Django 3.1.3 on 2020-11-29 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201120_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='fee_multiplier',
            new_name='additional_fee',
        ),
    ]
