# Generated by Django 3.1.7 on 2021-03-30 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201129_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='period',
            field=models.DecimalField(decimal_places=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
